/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adcb.xyz;

import com.adcb.util.MathUtil;

public class App {
    public String getGreeting() {
    	MathUtil.sum(5, 10);
        return "Hello world.";
    }

	/*
	 * public static void main(String[] args) { System.out.println(new
	 * App().getGreeting()); }
	 */
}
