/**
 * This java source file was generated by the Gradle 'init' task.
 */
package com.adcb.common;
/**
 * 
 * This is a library file.
 * 
 * @author aspire
 *
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
