/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adcb.xyz;

//import org.junit.Test;
//import static org.junit.Assert.*;
import org.junit.jupiter.api.Test;

import com.adcb.util.MathUtil;

import org.junit.jupiter.api.Assertions;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        Assertions.assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testMathUtilSum() {
    	int val = MathUtil.sum(10, 40);
        Assertions.assertNotNull(val);
    }
    @Test
    public void testDivide() {
    	Assertions.assertThrows(ArithmeticException.class, () -> {
            Integer.divideUnsigned(42, 0);
        });
    }
}
